# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import welcome_pb2 as welcome__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in welcome_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WelcomeServiceStub(object):
    """The welcome service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayWelcome = channel.unary_unary(
                '/welcome.WelcomeService/SayWelcome',
                request_serializer=welcome__pb2.WelcomeRequest.SerializeToString,
                response_deserializer=welcome__pb2.WelcomeResponse.FromString,
                _registered_method=True)


class WelcomeServiceServicer(object):
    """The welcome service definition.
    """

    def SayWelcome(self, request, context):
        """Sends a welcome message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WelcomeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayWelcome': grpc.unary_unary_rpc_method_handler(
                    servicer.SayWelcome,
                    request_deserializer=welcome__pb2.WelcomeRequest.FromString,
                    response_serializer=welcome__pb2.WelcomeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'welcome.WelcomeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('welcome.WelcomeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WelcomeService(object):
    """The welcome service definition.
    """

    @staticmethod
    def SayWelcome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/welcome.WelcomeService/SayWelcome',
            welcome__pb2.WelcomeRequest.SerializeToString,
            welcome__pb2.WelcomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
